feat: Added message for Holopin related questions
nhcarrigan/weLoveHacktoberfest pull request #431
Opened 2022-10-17 19:04 UTC by polarvoid

# Pull Request

## Description:

Adds a small message for queries regarding Holopin. I see a ton of questions on the HF server that are one of the following:
- Where are my Holopins?
- Why are my Holopins not showing up?

and quite often, they have either not opted-in to it, or it's in their spam :/

2022-10-17 19:06 UTC, polarvoid commented
Hey @naomi-lgbt I also noticed the `CONTRIBUTING` guidelines are outdated (I think?) with regard to the way the tags work currently with the '/' system.

2022-10-17 19:13 UTC, polarvoid commented
I just saw that there's a new `Claim it now` link too, maybe this could include that as well?

2022-10-18 21:23 UTC, naomi-lgbt requested changes
Let's soften the tone a bit and provide some additional information.

2022-10-18 21:23 UTC, naomi-lgbt commented on src/data/tags.ts
> +      "You have to opt-in via email for Holopin badges. Check your spam/trash before asking again.",
```suggestion
      "You have to opt-in via email for Holopin badges. If you opted in, make sure that the email did not land in your spam folder. Also, be sure that you opted in with the correct email address (not the GitHub no-reply email address). Finally, you should also see a `Claim Now` link in your Hacktoberfest profile.",
```

2022-10-18 21:34 UTC, naomi-lgbt approved these changes
banger pr, thanks for contributing!

2022-10-18 21:37 UTC, merged

2022-10-18 21:37 UTC, naomi-lgbt commented
## Congratulations

Congratulations on making your first pull request to our project. We have reviewed your contributions and are happy to accept them.

We hope you enjoyed the contribution process, and encourage you to watch for issues labelled `help wanted` for additional opportunities to contribute.

You can also see all open issues [through our contributor tool](https://contribute.naomi.lgbt)

2022-10-18 23:28 UTC, polarvoid commented
Awesome, thanks Naomi :)